CREATE DATABASE SENAI_DESAFIO_WISHLIST;

USE SENAI_DESAFIO_WISHLIST;

CREATE TABLE USUARIOS(
ID INT IDENTITY PRIMARY KEY,
EMAIL VARCHAR(250) NOT NULL,
SENHA VARCHAR(250) NOT NULL
);

CREATE TABLE DESEJOS (
ID INT IDENTITY PRIMARY KEY,
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID) NOT NULL,
DESCRICAO VARCHAR(250) NOT NULL);